### ISSUE TITLE
not receiving -name from docker-compose

### ISSUE THREAD

**Issue by cheater** [cpuguy83/docker-grand-ambassador#6]
Hi,
I have a service like this in docker-compose:

amb:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: '/usr/bin/grand-ambassador -name=app'

I tried with and without the single-quotes, with and without the equation sign swapping it for a space, and with double quotes... it still keeps on telling me:

amb_1 | time="2015-03-06T13:46:56Z" level=fatal msg="Missing required arguments _name_" 

I'm really stuck on this one.. please advise!

**Comment by cpuguy83** [comment]
This works for me:

``` yaml
test:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: -name foo
```
