### ISSUE TITLE
Container name with docker-composer

### ISSUE THREAD

**Issue by iamluc** [cpuguy83/docker-grand-ambassador#8]
Hi,

When using docker-composer with multiple instances, we can't provide the full name of the container because it varies (prefix/suffix)

It would be nice to have and option to tell the ambassador that docker-compose has been used and that it should search container with the same prefix and the same suffix.

So instead of

```
ambassador:
    image: cpuguy83/docker-grand-ambassador
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-name myproject_nginx_1"

nginx:
    build: docker/nginx
```

we could have something like

```
ambassador:
    image: cpuguy83/docker-grand-ambassador
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-compose -name nginx"

nginx:
    build: docker/nginx
```
